# Generated by Django 3.0.3 on 2020-04-09 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 19, 28, 38, 135532, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
