# Generated by Django 3.0.3 on 2020-04-10 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary', to='shop.PrimaryCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CIF', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('meanTime', models.FloatField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=shop.models.user_directory_path)),
                ('description', models.CharField(max_length=256)),
                ('admins', models.ManyToManyField(blank=True, related_name='shop', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_shop', to=settings.AUTH_USER_MODEL)),
                ('secondaryCategories', models.ManyToManyField(to='shop.SecondaryCategory')),
                ('services', models.ManyToManyField(blank=True, to='shop.Service')),
            ],
            options={
                'unique_together': {('CIF', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Dilluns'), (1, 'Dimarts'), (2, 'Dimecres'), (3, 'Dijous'), (4, 'Divendres'), (5, 'Dissabte'), (6, 'Diumenge')])),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shop.Shop')),
            ],
            options={
                'unique_together': {('day', 'startHour', 'shop')},
            },
        ),
    ]
