# Generated by Django 3.0.3 on 2020-04-08 15:55

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.user_directory_path),
        ),
    ]
