# Generated by Django 3.0.3 on 2020-04-07 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='admins',
            field=models.ManyToManyField(related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SecondaryCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary', to='shop.PrimaryCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='secondaryCategories',
            field=models.ManyToManyField(to='shop.SecondaryCategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='services',
            field=models.ManyToManyField(to='shop.Service'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='shop.Shop')),
            ],
            options={
                'unique_together': {('day', 'startHour', 'shop')},
            },
        ),
    ]
