# Generated by Django 3.0.3 on 2020-04-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Service'),
        ),
    ]
