# Generated by Django 3.0.3 on 2020-04-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200408_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='services',
            field=models.ManyToManyField(blank=True, to='shop.Service'),
        ),
    ]
