# Generated by Django 3.0.3 on 2020-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200409_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(default='Baboda es un ser especial muy bonito del area de', max_length=256),
            preserve_default=False,
        ),
    ]
