# Generated by Django 3.0.3 on 2020-04-10 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20200410_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
