# Generated by Django 3.0.3 on 2020-04-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200410_1053'),
        ('shop', '0006_auto_20200409_2104'),
    ]

    operations = [
    ]
