# Generated by Django 3.0.5 on 2020-04-06 20:34

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Full name')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_shopAdmin', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
