# Generated by Django 3.0.5 on 2020-04-06 16:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='Full name')),
                ('shopAdmin', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
