# Generated by Django 3.0.5 on 2020-04-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Email'),
        ),
    ]
